
varDictionaries:
  - name: "reaction"
    dictionary:
      - { value: 0, title: "UNDEFINED", color: 1 } # kBlack
      - { value: 1, title: "#nu_#mu + A #rightarrow reaction 1", colorHex: "#cfe8ff" }
      - { value: 2, title: "#nu_#mu + A #rightarrow reaction 2", colorHex: "#aabfe0" }
      - { value: 3, title: "#nu_#mu + A #rightarrow reaction 3", colorHex: "#9b9ed2" }
      - { value: 4, title: "#nu_#mu + A #rightarrow reaction 4", colorHex: "#5670c2" }
      - { value: 5, title: "#nu_#mu + A #rightarrow reaction 5", colorHex: "#293377" }
      - { value: 6, title: "#nu_#mu + A #rightarrow reaction 6", colorHex: "#1b1b52" }

histogramsDefinition:
  - varToPlot: "Raw"
    splitVars: [ "", "reaction" ]

  - varToPlot: "pmu"
    splitVars: [ "", "reaction" ]
    useSampleBinning: true # if not possible, error
    rescaleAsBinWidth: true # default true -> to look like a PDF
    rescaleBinFactor: 0.1 # / 100 MeV
#    xMax: 2000.
    xTitle: "p_{#mu} (GeV)"
    yTitle: "Counts / 100 MeV"
