

sampleSetConfig: "./inputs/fitter/likelihood/datasets/propagator/samples/config.yaml"

parametersManagerConfig: "./inputs/fitter/likelihood/datasets/propagator/parameters/config.yaml"

plotGeneratorConfig:    "./inputs/fitter/likelihood/datasets/propagator/plots/config.yaml"

